export const mockReportData = [
  {
    id: "B001",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    borrower: "John Smith",
    date: "2023-05-15",
    dueDate: "2023-06-15",
    status: "borrowed",
    type: "borrowed",
    bookType: "fiction",
  },
  {
    id: "B002",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    borrower: "Jane Doe",
    date: "2023-05-10",
    dueDate: "2023-06-10",
    status: "overdue",
    type: "overdue",
    bookType: "fiction",
  },
  {
    id: "B003",
    title: "1984",
    author: "George Orwell",
    borrower: "Alice Johnson",
    date: "2023-05-20",
    dueDate: "2023-06-20",
    status: "borrowed",
    type: "borrowed",
    bookType: "fiction",
  },
  {
    id: "B004",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    borrower: "Bob Williams",
    date: "2023-04-25",
    dueDate: "2023-05-25",
    status: "returned",
    type: "borrowDate",
    bookType: "fiction",
  },
  {
    id: "B005",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    borrower: "Carol Brown",
    date: "2023-05-05",
    dueDate: "2023-06-05",
    status: "borrowed",
    type: "dueDate",
    bookType: "fiction",
  },
  {
    id: "B006",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    borrower: "David Miller",
    date: "2023-04-15",
    dueDate: "2023-05-15",
    status: "overdue",
    type: "overdue",
    bookType: "fiction",
  },
  {
    id: "B007",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    borrower: "Emma Wilson",
    date: "2023-05-12",
    dueDate: "2023-06-12",
    status: "borrowed",
    type: "borrowed",
    bookType: "nonfiction",
  },
  {
    id: "B008",
    title: "The Origin of Species",
    author: "Charles Darwin",
    borrower: "Frank Thomas",
    date: "2023-05-08",
    dueDate: "2023-06-08",
    status: "borrowed",
    type: "borrowed",
    bookType: "nonfiction",
  },
  {
    id: "B009",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    borrower: "Grace Lee",
    date: "2023-04-30",
    dueDate: "2023-05-30",
    status: "overdue",
    type: "overdue",
    bookType: "nonfiction",
  },
  {
    id: "B010",
    title: "Principles of Physics",
    author: "David Halliday",
    borrower: "Henry Clark",
    date: "2023-05-18",
    dueDate: "2023-06-18",
    status: "borrowed",
    type: "borrowed",
    bookType: "textbook",
  },
]
